version: "3.8"

services:
  app:
    build: .
    container_name: linebot_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017/lineDB   # <--- aqui muda
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: linebot_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
