
PUT http://localhost:8080/lineBot/initSuport
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/exitSuport
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
POST http://localhost:8080/Product/new
Content-Type: application/json

{
  "data": {
    "name": "Colcha em Linho",
    "price": 30000,
    "description": "Colcha para berço em linho natural.",
    "isActive": true,
    "category": "64b2c55a1f8b9f24d7a8f0ab",
    "compDescription": "Colcha em linho natural com acabamento impecável, proporcionando conforto térmico e visual sofisticado.",
    "img": "[base64 image data]"
  }
}

####

GET http://localhost:8080/Product/allSalableActive


###
POST http://localhost:8080/SubProduct/new
Content-Type: application/json

{
  "productId": "687fe74a9eae629b57efab59",
  "data": {
    "parentProduct": "6878ff2b9337af0e27cbe33f",
    "bundlePrice": 120,
    "quantity": 1,
    "isEssential": false
  }
}


###
PUT http://localhost:8080/LineBot/allProducts

###
PUT http://localhost:8080/LineBot/allProducts

###

PUT http://localhost:8080/lineBot/selectProduct
Content-Type: application/json

{
  "id": "6878ff2b9337af0e27cbe33f",
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/addToOrcamento
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/saveOrcamento
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}


###
PUT http://localhost:8080/lineBot/ultimoOrcamento
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/custom/init
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/makeOrder
Content-Type: application/json

{
  "contact" : {
    "number" : "558498332658@c.us",
    "name" : "Gabriel Henrique"
  }
}

###
PUT http://localhost:8080/lineBot/custom/getExchangeableProducts
Content-Type: application/json

{
  "id" : "6880dec4cbbe552745ec8f9c"
}